-- 코드를 입력하세요

SELECT C.CAR_ID, C.CAR_TYPE, ROUND((C.DAILY_FEE * ((100 - P.DISCOUNT_RATE) *0.01))*30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
ON C.CAR_ID = H.CAR_ID 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ("세단", "SUV")
AND LEFT(P.DURATION_TYPE, 2) = 30
GROUP BY C.CAR_ID
HAVING MAX(H.END_DATE) <= "2022-11-01"
AND FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID ASC