-- 코드를 입력하세요
WITH MAX_TABLE AS 
    (
        SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAV
        FROM REST_INFO
        GROUP BY FOOD_TYPE
    )
    

SELECT INFO.FOOD_TYPE, INFO.REST_ID, INFO.REST_NAME, INFO.FAVORITES AS FAVORITES
FROM REST_INFO AS INFO
JOIN MAX_TABLE AS MT
ON INFO.FAVORITES = MT.MAX_FAV
GROUP BY INFO.FOOD_TYPE
ORDER BY INFO.FOOD_TYPE DESC;