-- 코드를 작성해주세요
WITH REF_TABLE AS
(
    SELECT T.ITEM_ID
    FROM ITEM_INFO AS I
    JOIN ITEM_TREE AS T
    ON I.ITEM_ID = T.PARENT_ITEM_ID
    WHERE I.RARITY = 'RARE'

)

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I
JOIN REF_TABLE AS R
ON I.ITEM_ID = R.ITEM_ID
ORDER BY I.ITEM_ID DESC