WITH RELEVANT_CARS AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) >= 5
),
MONTHLY_COUNTS AS (
    SELECT 
        MONTH(START_DATE) AS MONTH, 
        CAR_ID, 
        COUNT(HISTORY_ID) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE CAR_ID IN (SELECT CAR_ID FROM RELEVANT_CARS)
    AND YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY MONTH(START_DATE), CAR_ID
)
SELECT * FROM MONTHLY_COUNTS
ORDER BY MONTH ASC, CAR_ID DESC;